### ISSUE TITLE
Production Build does not generate index.html

### ISSUE THREAD

**Issue by TobiasPr** [issaafalkattan/React-Landing-Page-Template#44]
**Describe the bug**
The command `yarn build-prod` does not generate a index.html in `/out` directory. The index.html is instead in the `/out/404` directory

**To Reproduce**
1. `yarn install && yarn build-prod`
2. Check output of `out` directory
3. See error

**Expected behavior**
A index.html page should be generated in the `/out` dir -> `/out/index.html`

**Screenshots**
![image](https://user-images.githubusercontent.com/22955066/144817801-16a336aa-7769-49f2-987f-2581093b526a.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by issaafalkattan** [comment]
Looks like this issue is regarding another repo https://github.com/issaafalkattan/react-landing-page-template-2021, considering this one does not have a "yarn build-prod" command only a "yarn build" one.
