### ISSUE TITLE
Demo/Heroku Not working

### ISSUE THREAD

**Issue by deehill** [issaafalkattan/React-Landing-Page-Template#67]
Hi.

Not sure if this project is still being maintained. The Heroku Demo is not running from the link. Selecting the Link generates an error.

**Comment by gignupg** [comment]
+ 1

**Comment by issaafalkattan** [comment]
Thanks for reporting! I have deployed it on vercel instead: https://react-landing-page-template-93ne.vercel.app/

**Comment by gignupg** [comment]
Cool, thanks for updating the link!
