### ISSUE TITLE
On navigation click it does not scroll

### ISSUE THREAD

**Issue by Ruvim1999** [issaafalkattan/React-Landing-Page-Template#9]
Hi, on your demo when I click the nav buttons it is scrolling to the location, but when I try it locally it just jumps to the location, without scrolling. What am I missing here?

**Comment by sijin-raj** [comment]
check the code   If there some mistake check and slove it

**Comment by raynerhoward** [comment]
Smooth scrolling works elsewhere:

https://www.free-css.com/assets/files/free-css-templates/preview/page234/interact/
http://www.templatewire.com/preview/interact/

But it doesn't work with this particular repository. "Check the code if there some mistake check and slove it" is not a very useful comment.

**Comment by raynerhoward** [comment]
Found the solution:  https://stackoverflow.com/questions/26535990/smooth-scroll-doesnt-work

```
html {
  scroll-behavior: smooth;
}
```

Add this to the top of your public/css/style.css and voilà

**Comment by raynerhoward** [comment]
Also, remove the following line from public/index.html

`<script type="text/javascript" src="js/SmoothScroll.js"></script>`

That should do it.

**Comment by issaafalkattan** [comment]
Should be fixed now!
